apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: 087380303747.dkr.ecr.eu-west-2.amazonaws.com/goals_frontend:9eb172c9ebd104f205a783abc56dca5aed6eb81f
    name: frontend
    env:
      - name: REACT_APP_BACKEND_URL
        value: http://backend-svc
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
