apiVersion: v1
kind: Service
metadata:
  labels:
    run: frontend
  name: frontend-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  selector:
    run: frontend
  type: NodePort
status:
  loadBalancer: {}
