apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: 087380303747.dkr.ecr.eu-west-2.amazonaws.com/goals_frontend:a91b2059e727f7c0d0f89e0bf14126c946ae2120
    name: frontend
    env:
      - name: REACT_APP_BACKEND_URL
        value: http://backend-svc
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
